// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RatBot.Infrastructure.Data;

#nullable disable

namespace RatBot.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20261002204211_RemoveUserTimezones")]
    partial class RemoveUserTimezones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RatBot.Domain.Features.Logging.LoggingConfiguration", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long?>("DeleteLogChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("delete_log_channel_id");

                    b.Property<long?>("EditLogChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("edit_log_channel_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<TimeSpan>("EvidenceRetentionPeriod")
                        .HasColumnType("interval")
                        .HasColumnName("evidence_retention_period");

                    b.HasKey("GuildId");

                    b.ToTable("logging_configurations", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Features.Logging.LoggingExcludedChannel", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("ExcludedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("excluded_at_utc");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("logging_excluded_channels", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Features.Logging.MessageLogEntry", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("OriginalMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("original_message_id");

                    b.Property<long>("LogMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("log_message_id");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.HasKey("GuildId", "OriginalMessageId", "LogMessageId");

                    b.HasIndex("GuildId", "LogMessageId");

                    b.ToTable("message_log_entries", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Features.Logging.ObservedMessage", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("OriginalMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("original_message_id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.HasKey("GuildId", "OriginalMessageId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GuildId", "ChannelId");

                    b.ToTable("observed_messages", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Features.Meta.MetaProposalState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("FailedPollAttempts")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastPublicationRetryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivation")
                        .HasMaxLength(1950)
                        .HasColumnType("character varying(1950)");

                    b.Property<long>("OriginalThreadAuthorUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("PollExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PollFinalizationRetries")
                        .HasColumnType("integer");

                    b.Property<long?>("PollMessageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProposalAuthorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProposalThreadChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProposalTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ProposedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("PublicationErrorMessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("PublicationRetryFailures")
                        .HasColumnType("integer");

                    b.Property<string>("Specification")
                        .HasMaxLength(1950)
                        .HasColumnType("character varying(1950)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("SuggestionThreadChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("SuggestionsForumChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Summary")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<DateTimeOffset>("TrackedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VetoReason")
                        .HasMaxLength(1950)
                        .HasColumnType("character varying(1950)");

                    b.Property<DateTimeOffset?>("VetoedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("VetoedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("Status");

                    b.HasIndex("GuildId", "PollMessageId");

                    b.HasIndex("GuildId", "ProposalThreadChannelId");

                    b.HasIndex("GuildId", "SuggestionThreadChannelId")
                        .IsUnique();

                    b.HasIndex("Status", "PollExpiresAtUtc");

                    b.ToTable("MetaProposalStates", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Features.Meta.MetaSuggestionSettings", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("CabinetChairRoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("CabinetRoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommitteeRoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProposalsForumChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("SuggestionsForumChannelId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("MetaSuggestionSettings", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Moderation.AutobannedUser", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("BannedUser")
                        .HasColumnType("bigint");

                    b.Property<long>("Moderator")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId", "BannedUser");

                    b.HasIndex("BannedUser");

                    b.HasIndex("GuildId");

                    b.HasIndex("Moderator");

                    b.ToTable("AutobannedUsers", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Moderation.ImageSpamSettings", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("BurstDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("RequiredAttachmentCount")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredChannelCount")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("ImageSpamSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImageSpamSettings_BurstDurationSeconds_Positive", "\"BurstDurationSeconds\" > 0");

                            t.HasCheckConstraint("CK_ImageSpamSettings_RequiredAttachmentCount_Positive", "\"RequiredAttachmentCount\" > 0");

                            t.HasCheckConstraint("CK_ImageSpamSettings_RequiredChannelCount_Positive", "\"RequiredChannelCount\" > 0");
                        });
                });

            modelBuilder.Entity("RatBot.Features.EmojiAnalytics.EmojiUsageCount", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmojiId")
                        .HasColumnType("bigint");

                    b.Property<int>("MessageUsageCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReactionUsageCount")
                        .HasColumnType("int");

                    b.HasKey("GuildId", "EmojiId");

                    b.ToTable("EmojiUsageCounts", (string)null);
                });

            modelBuilder.Entity("RatBot.Features.RoleColours.MemberColourPreference", b =>
                {
                    b.Property<Guid>("PreferenceId")
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SelectedOptionId")
                        .HasColumnType("uuid");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PreferenceId");

                    b.HasIndex("GuildId", "SelectedOptionId");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("MemberColourPreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_MemberColourPreferences_ConfiguredOption_SelectedOption_NotNull", "(\"Kind\" <> 1) OR (\"SelectedOptionId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_MemberColourPreferences_NoColour_SelectedOption_Null", "(\"Kind\" <> 2) OR (\"SelectedOptionId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("RatBot.Features.RoleColours.RoleColourOption", b =>
                {
                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DisplayRoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalisedKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SourceRoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OptionId");

                    b.HasIndex("GuildId", "DisplayRoleId")
                        .IsUnique();

                    b.HasIndex("GuildId", "NormalisedKey")
                        .IsUnique();

                    b.HasIndex("GuildId", "SourceRoleId")
                        .IsUnique();

                    b.HasIndex("GuildId", "SourceRoleId", "DisplayRoleId")
                        .IsUnique();

                    b.ToTable("RoleColourOptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoleColourOptions_DifferentRoles", "\"SourceRoleId\" <> \"DisplayRoleId\"");

                            t.HasCheckConstraint("CK_RoleColourOptions_Key_NotBlank", "length(btrim(\"Key\")) > 0");

                            t.HasCheckConstraint("CK_RoleColourOptions_Label_NotBlank", "length(btrim(\"Label\")) > 0");
                        });
                });

            modelBuilder.Entity("RatBot.Features.RoleColours.MemberColourPreference", b =>
                {
                    b.HasOne("RatBot.Features.RoleColours.RoleColourOption", null)
                        .WithMany()
                        .HasForeignKey("GuildId", "SelectedOptionId")
                        .HasPrincipalKey("GuildId", "OptionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
